function [fitresult, gof] = createFitSigmoid(testDepths, popPol)
%CREATEFIT(TESTDEPTHS,POPPOL)
%  Create a fit.
%
%  Data for 'fit1' fit:
%      X Input : testDepths
%      Y Output: popPol
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Jan-2022 17:49:28


%% Fit: 'fit1'.
[xData, yData] = prepareCurveData( testDepths, popPol );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

feval(fitresult,xData)

% Plot fit with data.
figure( 'Name', 'fit1' );
h = plot( fitresult, xData, yData );
legend( h, 'popPol vs. testDepths', 'fit1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'testDepths', 'Interpreter', 'none' );
ylabel( 'popPol', 'Interpreter', 'none' );
grid on


